[package]
name = "cargo-prompt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
rustminify = "0.2.0"
syn = { version = "1.0", features = ["parsing", "full"] }
walkdir = "2.5.0"
